#!/usr/bin/env python3
"""Generate cmm.gbnf (llama.cpp) from cmm.lark — mechanical and deterministic.

Rules convert token-by-token (the .lark file is written in a restricted
dialect: literals, terminal refs, rule refs, parens, ?, *, +, |). Terminals
convert via TERMINAL_MAP, which pins the EXACT lark regex source — if the
.lark terminal changes, this script fails loudly instead of drifting.

DOCUMENTED WIDENING: GBNF has no lookahead, so NAME cannot exclude keywords
("if" matches NAME in the GBNF target). The GBNF mask therefore over-accepts
keyword-as-identifier; the Lark artifact is exact. For generation masking,
over-acceptance never blocks a valid program; the Rust parser remains the
final oracle.

Usage: tools/grammar/lark2gbnf.py   (writes tools/grammar/cmm.gbnf)
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "cmm.lark"
OUT = HERE / "cmm.gbnf"

# (exact lark regex source) -> gbnf production body
TERMINAL_MAP = {
    "NUMBER": (
        r"/[0-9]+(\.[0-9]+)?([ui](8|16|32|64))?/",
        '[0-9]+ ("." [0-9]+)? ([ui] ("8" | "16" | "32" | "64"))?',
    ),
    "INT": (r"/[0-9]+/", "[0-9]+"),
    "STRING": (
        r'/"(\\.|[^"\\])*"/',
        '"\\"" ("\\\\" [^\\n] | [^\\"\\\\\\n])* "\\""',
    ),
    "TNAME": (r"/[A-Z][A-Za-z0-9_]*/", "[A-Z] [A-Za-z0-9_]*"),
    "NAME": (
        r"/(?!(?:if|else|while|for|in|match|type|ret|go|pub|and|or|not)(?![A-Za-z0-9_]))[a-z_][A-Za-z0-9_]*/",
        # widened: no lookahead in GBNF (see module docstring)
        "[a-z_] [A-Za-z0-9_]*",
    ),
    "WS": (r"/[ \t]+/", "[ \\t]+"),
    "NL": (
        r"/[ \t]*(#[^\n]*)?\r?\n([ \t]*(#[^\n]*)?\r?\n)*[ \t]*/",
        '[ \\t]* ("#" [^\\n]*)? "\\r"? "\\n" ([ \\t]* ("#" [^\\n]*)? "\\r"? "\\n")* [ \\t]*',
    ),
}

TOKEN_RE = re.compile(
    r'\s*(?:(?P<lit>"(?:\\.|[^"\\])*")|(?P<term>[A-Z][A-Z0-9_]*)'
    r"|(?P<rule>_?[a-z][a-z0-9_]*)|(?P<sym>[()|?*+]))"
)


def gbnf_name(lark_name: str) -> str:
    return lark_name.lstrip("_").replace("_", "-")


def convert_rhs(rhs: str, rules: set, terminals: set, line: str) -> str:
    out, pos = [], 0
    while pos < len(rhs):
        m = TOKEN_RE.match(rhs, pos)
        if not m:
            if rhs[pos:].strip():
                sys.exit(f"unconvertible token at: {rhs[pos:]!r} in {line!r}")
            break
        pos = m.end()
        if m.group("lit"):
            out.append(m.group("lit"))
        elif m.group("term"):
            if m.group("term") not in terminals:
                sys.exit(f"unknown terminal {m.group('term')} in {line!r}")
            out.append(gbnf_name(m.group("term").lower()))
        elif m.group("rule"):
            if m.group("rule") not in rules:
                sys.exit(f"unknown rule {m.group('rule')} in {line!r}")
            out.append(gbnf_name(m.group("rule")))
        else:
            sym = m.group("sym")
            if sym in "?*+" and out:
                out[-1] = out[-1] + sym
            else:
                out.append(sym)
    # re-join, keeping ?,*,+ glued and |,(,) spaced
    text = " ".join(out)
    return re.sub(r"\(\s+", "(", re.sub(r"\s+\)", ")", text))


def main() -> None:
    rule_lines, term_lines = [], []
    for raw in SRC.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        name = line.split(":", 1)[0].strip()
        if re.fullmatch(r"[A-Z][A-Z0-9_]*", name):
            term_lines.append(line)
        elif re.fullmatch(r"_?[a-z][a-z0-9_]*", name):
            rule_lines.append(line)
        else:
            sys.exit(f"unparsable line: {line!r}")

    rules = {l.split(":", 1)[0].strip() for l in rule_lines}
    terminals = {l.split(":", 1)[0].strip() for l in term_lines}

    # whitespace plumbing: the lark side spells these as rule->terminal
    # aliases (_ws: WS?, ws1: WS, _nl: NL); flattened here so the sanitized
    # rule name and the terminal name don't collide (both would be "ws").
    ALIASES = {
        "_ws": "[ \\t]*",
        "ws1": "[ \\t]+",
        "_nl": TERMINAL_MAP["NL"][1],
    }
    ALIAS_TERMINALS = {"WS", "NL"}

    out = [
        "# cmm v0.1 GBNF (llama.cpp) — GENERATED by lark2gbnf.py from cmm.lark.",
        "# Do not hand-edit. NAME is widened vs the Lark artifact (no lookahead",
        "# in GBNF): keywords match NAME here; the Rust parser is the oracle.",
        "",
        "root ::= start",
    ]
    for line in rule_lines:
        name, rhs = (part.strip() for part in line.split(":", 1))
        if name in ALIASES:
            out.append(f"{gbnf_name(name)} ::= {ALIASES[name]}")
            continue
        out.append(f"{gbnf_name(name)} ::= {convert_rhs(rhs, rules, terminals, line)}")
    for line in term_lines:
        name, rhs = (part.strip() for part in line.split(":", 1))
        want_src, body = TERMINAL_MAP[name]
        if rhs != want_src:
            sys.exit(
                f"terminal {name} changed in cmm.lark ({rhs!r}) but TERMINAL_MAP "
                f"still pins {want_src!r} — update the map deliberately"
            )
        if name in ALIAS_TERMINALS:
            continue  # flattened into the alias rules above
        out.append(f"{gbnf_name(name.lower())} ::= {body}")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT.name}: {len(rule_lines)} rules + {len(term_lines)} terminals")


if __name__ == "__main__":
    main()
