// Reproducible build for the static playground.
//   1. generate src/generated/data.js from the repo corpus + grammar results
//   2. bundle src/app.js (+ wasi shim, js-tiktoken, o200k ranks) → dist/app.bundle.js
//   3. copy the wasm32-wasip1 curt.wasm next to index.html
// The output (dist/app.bundle.js, curt.wasm, src/generated/data.js) is committed
// so a static host (HF Space, `python -m http.server`) serves it with no build.
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, copyFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const corpusDir = join(repo, "corpus");

// ---- 1. examples (curt + Python twins) ------------------------------------
function pretty(base) {
  return base.replace(/^\d+_/, "").replace(/_/g, " ");
}
const curtFiles = readdirSync(corpusDir).filter((f) => f.endsWith(".curt")).sort();
const examples = curtFiles.map((f) => {
  const base = f.slice(0, -5);
  const ex = { name: pretty(base), curt: readFileSync(join(corpusDir, f), "utf8") };
  const py = join(corpusDir, base + ".py");
  if (existsSync(py)) ex.py = readFileSync(py, "utf8");
  return ex;
});

// ---- 2. constrained-decode gallery ----------------------------------------
const gres = JSON.parse(readFileSync(join(repo, "tools", "grammar", "results.json"), "utf8"));
const con = gres.constrained;
const gallery = {
  blurb:
    "An 8B OSS model with zero curt knowledge in its weights, generating under a GBNF " +
    "grammar mask derived from the reference grammar. The mask is the reliability floor: " +
    "every sample below was validated by the real `curt parse` — the parser is the oracle.",
  stats: [
    { value: `${Math.round(con.rate * 100)}%`, label: `parse-valid (${con.parse_ok}/${con.n}, grammar-masked)` },
    { value: "0", label: "mid-stream syntax violations in 200 generations" },
    { value: "44%", label: "parse-valid unconstrained (same prompts)" },
  ],
  samples: con.samples.map((s) => ({ out: s.out, parses: !!s.parses })),
};

// ---- emit the generated data module ---------------------------------------
const genDir = join(here, "src", "generated");
mkdirSync(genDir, { recursive: true });
const banner = "// GENERATED by build.mjs from repo corpus + tools/grammar/results.json. Do not edit.\n";
writeFileSync(
  join(genDir, "data.js"),
  banner +
    `export const EXAMPLES = ${JSON.stringify(examples)};\n` +
    `export const GALLERY = ${JSON.stringify(gallery)};\n`
);

// ---- 3. bundle -------------------------------------------------------------
mkdirSync(join(here, "dist"), { recursive: true });
await esbuild.build({
  entryPoints: [join(here, "src", "app.js")],
  bundle: true,
  format: "esm",
  minify: true,
  sourcemap: false,
  target: ["es2022"],
  outfile: join(here, "dist", "app.bundle.js"),
  logLevel: "info",
});

// ---- 4. copy the wasm artifact --------------------------------------------
const wasmSrc = join(repo, "target", "wasm32-wasip1", "release", "curt.wasm");
copyFileSync(wasmSrc, join(here, "curt.wasm"));

console.log(`built: ${examples.length} examples, ${gallery.samples.length} gallery samples`);
